/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcAnteprima {
        "abstract": string;
        "dataevento": string;
        "datapubblicazione": string;
        "descrizione": string;
        "durata": string;
        "img": string;
        "link": string;
        "luogo": string;
        "orario": string;
        "showimage": boolean;
        "titolo": string;
        "web": string;
    }
    interface WcVideo {
        "dataevento": string;
        "datapubblicazione": string;
        "descrizione": string;
        "durata": string;
        "img": string;
        "luogo": string;
        "orario": string;
        "titolo": string;
        "video": string;
    }
}
export interface WcAnteprimaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcAnteprimaElement;
}
export interface WcVideoCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcVideoElement;
}
declare global {
    interface HTMLWcAnteprimaElement extends Components.WcAnteprima, HTMLStencilElement {
    }
    var HTMLWcAnteprimaElement: {
        prototype: HTMLWcAnteprimaElement;
        new (): HTMLWcAnteprimaElement;
    };
    interface HTMLWcVideoElement extends Components.WcVideo, HTMLStencilElement {
    }
    var HTMLWcVideoElement: {
        prototype: HTMLWcVideoElement;
        new (): HTMLWcVideoElement;
    };
    interface HTMLElementTagNameMap {
        "wc-anteprima": HTMLWcAnteprimaElement;
        "wc-video": HTMLWcVideoElement;
    }
}
declare namespace LocalJSX {
    interface WcAnteprima {
        "abstract"?: string;
        "dataevento"?: string;
        "datapubblicazione"?: string;
        "descrizione"?: string;
        "durata"?: string;
        "img"?: string;
        "link"?: string;
        "luogo"?: string;
        "onEventMappa"?: (event: WcAnteprimaCustomEvent<any>) => void;
        "onEventShare"?: (event: WcAnteprimaCustomEvent<any>) => void;
        "orario"?: string;
        "showimage"?: boolean;
        "titolo"?: string;
        "web"?: string;
    }
    interface WcVideo {
        "dataevento"?: string;
        "datapubblicazione"?: string;
        "descrizione"?: string;
        "durata"?: string;
        "img"?: string;
        "luogo"?: string;
        "onEventMappa"?: (event: WcVideoCustomEvent<any>) => void;
        "onEventShare"?: (event: WcVideoCustomEvent<any>) => void;
        "onEventVideo"?: (event: WcVideoCustomEvent<any>) => void;
        "orario"?: string;
        "titolo"?: string;
        "video"?: string;
    }
    interface IntrinsicElements {
        "wc-anteprima": WcAnteprima;
        "wc-video": WcVideo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-anteprima": LocalJSX.WcAnteprima & JSXBase.HTMLAttributes<HTMLWcAnteprimaElement>;
            "wc-video": LocalJSX.WcVideo & JSXBase.HTMLAttributes<HTMLWcVideoElement>;
        }
    }
}
