/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ClaudioComponent {
    }
}
declare global {
    interface HTMLClaudioComponentElement extends Components.ClaudioComponent, HTMLStencilElement {
    }
    var HTMLClaudioComponentElement: {
        prototype: HTMLClaudioComponentElement;
        new (): HTMLClaudioComponentElement;
    };
    interface HTMLElementTagNameMap {
        "claudio-component": HTMLClaudioComponentElement;
    }
}
declare namespace LocalJSX {
    interface ClaudioComponent {
    }
    interface IntrinsicElements {
        "claudio-component": ClaudioComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "claudio-component": LocalJSX.ClaudioComponent & JSXBase.HTMLAttributes<HTMLClaudioComponentElement>;
        }
    }
}
