image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
  BLOB: "$BLOB_URL$CNAME$TOKEN"
  CACHE: '60'
stages:
  - build
  - deploy

build:
  stage: build
  image: smartcommunitylab/modular-app:android
  environment:
    name: develop
  artifacts:
    paths:
      - modular-app/www/
  script:
    - cd modular-app
    # - npm install && ionic cordova platform add android
    - ionic cordova platform add android
    - ng run app:ionic-cordova-build --platform=android
  only:
    - deploy-prod

deploy:
  stage: deploy
  image: smartcommunitylab/cordova-hcp:slim
  environment:
    name: develop
  dependencies:
    - build
  script:
    - cd modular-app
    - /cordova-hpc/node_modules/.bin/cordova-hcp build
    - azcopy copy './www/*' $BLOB --recursive --cache-control $CACHE --overwrite 'true'
  only:
    - deploy-prod
