/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface WcTrasportiTable {
    'accessibility': boolean;
    'arrows': boolean;
    'citta': string;
    'color': string;
    'data': string;
    'day': string;
    'font': string;
    'labeldelay': string;
    'labeltrips': string;
    'numero': string;
    'showtrips': boolean;
    'title': string;
  }
  interface WcTrasportiTableAttributes extends StencilHTMLAttributes {
    'accessibility'?: boolean;
    'arrows'?: boolean;
    'citta'?: string;
    'color'?: string;
    'data'?: string;
    'day'?: string;
    'font'?: string;
    'labeldelay'?: string;
    'labeltrips'?: string;
    'numero'?: string;
    'onChangeDateEvent'?: (event: CustomEvent) => void;
    'onShowStopEvent'?: (event: CustomEvent) => void;
    'showtrips'?: boolean;
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WcTrasportiTable': Components.WcTrasportiTable;
  }

  interface StencilIntrinsicElements {
    'wc-trasporti-table': Components.WcTrasportiTableAttributes;
  }


  interface HTMLWcTrasportiTableElement extends Components.WcTrasportiTable, HTMLStencilElement {}
  var HTMLWcTrasportiTableElement: {
    prototype: HTMLWcTrasportiTableElement;
    new (): HTMLWcTrasportiTableElement;
  };

  interface HTMLElementTagNameMap {
    'wc-trasporti-table': HTMLWcTrasportiTableElement
  }

  interface ElementTagNameMap {
    'wc-trasporti-table': HTMLWcTrasportiTableElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
