/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  TipoDefunto,
  TipoFunerale,
} from './components/Dati/tipoDatiFunerali';


export namespace Components {

  interface DettaglioMorte {
    'defunto': TipoDefunto;
    'funerale': TipoFunerale;
    'isFunerale': boolean;
  }
  interface DettaglioMorteAttributes extends StencilHTMLAttributes {
    'defunto'?: TipoDefunto;
    'funerale'?: TipoFunerale;
    'isFunerale'?: boolean;
    'onCondividi'?: (event: CustomEvent) => void;
    'onIndicazioni'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DettaglioMorte': Components.DettaglioMorte;
  }

  interface StencilIntrinsicElements {
    'dettaglio-morte': Components.DettaglioMorteAttributes;
  }


  interface HTMLDettaglioMorteElement extends Components.DettaglioMorte, HTMLStencilElement {}
  var HTMLDettaglioMorteElement: {
    prototype: HTMLDettaglioMorteElement;
    new (): HTMLDettaglioMorteElement;
  };

  interface HTMLElementTagNameMap {
    'dettaglio-morte': HTMLDettaglioMorteElement
  }

  interface ElementTagNameMap {
    'dettaglio-morte': HTMLDettaglioMorteElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
